LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/company-2025.10.13.csv'
INTO TABLE registru_md_04_12_2025
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(IDNO, DATA_REG, DEN_COM, FORMA_ORG, ADRESA, LIST_COND, LISTA_FOND, GEN_ACT_NE_LIC, GEN_ACT_LIC, DATE_OF_LIQUID, STATUTUL_DATE, STATUTUL);
