CREATE TABLE `reg_cfp_06_21` (
	`id` BIGINT NOT NULL,
	`DENUMIRE` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`VALUE` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`act` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `index_id` (`id`) USING BTREE,
	INDEX `index_VALUE` (`VALUE`) USING BTREE,
	INDEX `index_DENUMIRE` (`DENUMIRE`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
