CREATE TABLE `reg_cuatm_06_21` (
	`id_cu` BIGINT  NOT NULL,
	`DEN_CUATM` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`NUMBER_CUATM` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`source` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`id_cu`) USING BTREE,
	UNIQUE INDEX `index_id` (`id_cu`) USING BTREE,
	INDEX `index_DEN_CUATM` (`DEN_CUATM`) USING BTREE,
	INDEX `index_NUMBER_CUATM` (`NUMBER_CUATM`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
