CREATE TABLE `registru_md_04_26_2021` (
	`IDNO` BIGINT(19) NULL DEFAULT NULL,
	`DATA_REG` DATE NULL DEFAULT NULL,
	`DEN_COM` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`FORMA_ORG` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`ADRESA` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`LIST_COND` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`LISTA_FOND` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`GEN_ACT_NE_LIC` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`GEN_ACT_LIC` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`STATUTUL` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8_general_ci'
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

