CREATE TABLE `reg_06_01_21_vw` (
	`id_vw` BIGINT(19) NOT NULL DEFAULT '0',
	`DEN_COM_VW` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`died` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`IDNO_VW` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`ADRESA_VW` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`FORMA_ORG_VW` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`dob` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`LIST_COND_VW` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`LISTA_FOND_VW` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`GEN_ACT_NE_LIC_VW` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`GEN_ACT_LIC_VW` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`STATUTUL_VW` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`DATA_REG_VW` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`personalinfo` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`id_vw`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;