CREATE TABLE `VW_CUATM` (
	`CODUL` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`DENUMIRE` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`GRUPA` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`ORDINE` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`FULL_CODE` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `PRGS` VARCHAR(2) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci'

)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
