CREATE TABLE `CL_CUATM74` (
	`CODUL7` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`CODUL4` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci'


)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
