--DROP TABLE USER_BANCU.VW_CL_CUATM_VER2 CASCADE CONSTRAINTS;

CREATE TABLE USER_BANCU.VW_CL_CUATM_VER2
(
  CODUL      VARCHAR2(7 BYTE)                    NOT NULL,
  GRUPA      VARCHAR2(7 BYTE)                    NOT NULL,
  DENUMIRE   VARCHAR2(255 BYTE)                  NOT NULL,
  RAION_DENUMIRE   VARCHAR2(1024 BYTE)           ,
  ORDINE     INTEGER,
  PRGS       VARCHAR2(2 BYTE),
  FULL_CODE   VARCHAR2(1024 BYTE)               
)
TABLESPACE TBS_DTI_USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (    
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

/*