CREATE TABLE `id_vw_ver2` (
	`id_vw` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`DEN_COM_VW` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`died` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`IDNO_VW` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`ADRESA_VW` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `DENUMIRE_CUATM` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `RAION_DENUMIRE` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `FULL_NAME` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `FORMA_ORG_VW` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `dob` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `LIST_COND_VW` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `LISTA_FOND_VW` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `GEN_ACT_NE_LIC_VW` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `GEN_ACT_LIC_VW` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `STATUTUL_VW` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `DATA_REG_VW` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `personalinfo` VARCHAR(254) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `DATE_OF_LIQUID` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `STATUTUL_DATE` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `CUATM` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `LISTA_BENIF` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `TARI` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `TARI_DENUMIRE` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `CODUL4` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `CODUL7` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
   `FULL_CODE` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci'


)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;




-- D.id_vw,
--  D.DEN_COM_VW,
--  D.died,
--  D.IDNO_VW,
--  D.ADRESA_VW,
--  C.DENUMIRE DENUMIRE_CUATM,

--  C.RAION_DENUMIRE,
--  CONCAT(C.DENUMIRE,' - ',RAION_DENUMIRE) AS FULL_NAME,
--  D.FORMA_ORG_VW, 
--  D.dob,
--  D.LIST_COND_VW,
--  D.LISTA_FOND_VW,
--  D.GEN_ACT_NE_LIC_VW,
--  D.GEN_ACT_LIC_VW,
--  D.STATUTUL_VW,
--  D.DATA_REG_VW,
--  D.personalinfo,
--  D.DATE_OF_LIQUID,
--  D.STATUTUL_DATE,
--  D.CUATM, 
--  D.LISTA_BENIF,
--  NULL TARI,
--  NULL TARI_DENUMIRE,
--  L.CODUL4,
--  L.CODUL7,
--  C.FULL_CODE