
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/company-2025.05.12-clean.csv'
INTO TABLE registru_md_04_12_2025
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(
  @IDNO_RAW,
  @DATA_REG_RAW, 
  DEN_COM, 
  FORMA_ORG, 
  ADRESA, 
  LIST_COND, 
  LISTA_FOND, 
  GEN_ACT_NE_LIC, 
  GEN_ACT_LIC, 
  @DATE_OF_LIQUID_RAW, 
  @STATUTUL_DATE_RAW, 
  STATUTUL
)
SET 
  IDNO = IF(TRIM(@IDNO_RAW) = '', NULL, @IDNO_RAW),
  DATA_REG = IF(TRIM(@DATA_REG_RAW) = '', NULL, STR_TO_DATE(TRIM(@DATA_REG_RAW), '%m/%d/%Y')),
  DATE_OF_LIQUID = IF(TRIM(@DATE_OF_LIQUID_RAW) = '', NULL, STR_TO_DATE(TRIM(@DATE_OF_LIQUID_RAW), '%m/%d/%Y')),
  STATUTUL_DATE = IF(TRIM(@STATUTUL_DATE_RAW) = '', NULL, STR_TO_DATE(TRIM(@STATUTUL_DATE_RAW), '%m/%d/%Y'));
