LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/company_2026.04.14.csv'
INTO TABLE registru_md_09_29_2025
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(
  @IDNO_RAW,
  @DATA_REG_RAW,
  @DEN_COM_RAW,
  @FORMA_ORG_RAW,
  @ADRESA_RAW,
  @LIST_COND_RAW,
  @LISTA_FOND_RAW,
  @GEN_ACT_NE_LIC_RAW,
  @GEN_ACT_LIC_RAW,
  @DATE_OF_LIQUID_RAW,
  @STATUTUL_DATE_RAW,
  @STATUTUL_RAW
)
SET
  IDNO = CASE
           WHEN TRIM(@IDNO_RAW) = '' OR LOWER(TRIM(@IDNO_RAW)) = 'null' THEN NULL
           ELSE CAST(TRIM(@IDNO_RAW) AS UNSIGNED)
         END,
  DATA_REG = CASE
               WHEN TRIM(@DATA_REG_RAW) = '' OR LOWER(TRIM(@DATA_REG_RAW)) = 'null' THEN NULL
               ELSE STR_TO_DATE(TRIM(@DATA_REG_RAW), '%d.%m.%Y')
             END,
  DEN_COM = NULLIF(TRIM(@DEN_COM_RAW), ''),
  FORMA_ORG = NULLIF(TRIM(@FORMA_ORG_RAW), ''),
  ADRESA = NULLIF(TRIM(@ADRESA_RAW), ''),
  LIST_COND = NULLIF(TRIM(@LIST_COND_RAW), ''),
  LISTA_FOND = NULLIF(TRIM(@LISTA_FOND_RAW), ''),
  GEN_ACT_NE_LIC = NULLIF(TRIM(@GEN_ACT_NE_LIC_RAW), ''),
  GEN_ACT_LIC = NULLIF(TRIM(@GEN_ACT_LIC_RAW), ''),
  DATE_OF_LIQUID = CASE
                     WHEN TRIM(@DATE_OF_LIQUID_RAW) = '' OR LOWER(TRIM(@DATE_OF_LIQUID_RAW)) = 'null' THEN NULL
                     ELSE STR_TO_DATE(TRIM(@DATE_OF_LIQUID_RAW), '%d.%m.%Y')
                   END,
  STATUTUL_DATE = CASE
                    WHEN TRIM(@STATUTUL_DATE_RAW) = '' OR LOWER(TRIM(@STATUTUL_DATE_RAW)) = 'null' THEN NULL
                    ELSE STR_TO_DATE(TRIM(@STATUTUL_DATE_RAW), '%d.%m.%Y')
                  END,
  STATUTUL = NULLIF(TRIM(@STATUTUL_RAW), '');