CREATE TABLE `id_registru_06_17_24` (
	`ID` BIGINT(19) NULL DEFAULT NULL,
	`IDNO` BIGINT(19) NULL DEFAULT NULL,
	`DATA_REG` DATE NULL DEFAULT NULL,
	`DEN_COM` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`FORMA_ORG` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`ADRESA` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`LIST_COND` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`LISTA_FOND` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`GEN_ACT_NE_LIC` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`GEN_ACT_LIC` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`DATE_OF_LIQUID` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`STATUTUL_DATE` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`STATUTUL` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci'
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
