CREATE TABLE `registru_md_01_17_2022` (
	`IDNO` BIGINT(19) NULL DEFAULT NULL,
	`DATA_REG` DATE NULL DEFAULT NULL,
	`DEN_COM` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`FORMA_ORG` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`ADRESA` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`LIST_COND` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`LISTA_FOND` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`GEN_ACT_NE_LIC` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`GEN_ACT_LIC` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`DATE_OF_LIQUID` DATE NULL DEFAULT NULL,
	`STATUTUL_DATE` DATE NULL DEFAULT NULL,
	`STATUTUL` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci'
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
