-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.42 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.11.0.7074
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table u331875177_db2.start3v5
CREATE TABLE IF NOT EXISTS `start3v5` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `statut` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'xxxxx',
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `galaxy` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `star` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `dob` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '0000-00-00',
  `serviciu` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `sectia` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `depart` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `phoneinternal` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `personalinfo` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `formname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `phonemobil` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `created_date` datetime NOT NULL DEFAULT (now()),
  `floor` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `office` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  `remove_date` datetime DEFAULT NULL,
  `date_updated` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `recoverydata` datetime DEFAULT NULL,
  `notice` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil.',
  `studio` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'empty field',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `index_id` (`id`) USING BTREE,
  KEY `index_name` (`name`) USING BTREE,
  KEY `index_description` (`description`) USING BTREE,
  KEY `index_galaxy` (`galaxy`) USING BTREE,
  KEY `index_star` (`star`) USING BTREE,
  KEY `index_serviciu` (`serviciu`) USING BTREE,
  KEY `index_sectia` (`sectia`) USING BTREE,
  KEY `index_depart` (`depart`) USING BTREE,
  KEY `index_phone` (`phone`) USING BTREE,
  KEY `index_email` (`email`) USING BTREE,
  KEY `index_phonemobil` (`phonemobil`) USING BTREE,
  KEY `index_died` (`statut`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=719 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table u331875177_db2.start3v5: ~87 rows (approximately)
REPLACE INTO `start3v5` (`id`, `name`, `statut`, `description`, `galaxy`, `star`, `dob`, `serviciu`, `sectia`, `depart`, `phone`, `phoneinternal`, `email`, `personalinfo`, `formname`, `phonemobil`, `created_date`, `floor`, `office`, `remove_date`, `date_updated`, `recoverydata`, `notice`, `studio`) VALUES
	(3, 'BANCU Vitalie', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Programator principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia proiectare aplicaţii', '+37322403021', '121', 'vitalie.bancu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770604', '2020-04-20 16:49:56', '1', '103', '2021-07-15 17:17:34', '2025-07-30 16:07:44', '2021-07-15 17:18:16', 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(4, 'Mirzac Ion', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sef directie generala tehnologii informationale', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'empty field', '+37322403010', '110', 'ion.mirzac@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770014', '2020-04-20 16:49:56', 'empty field', 'empty field', '2025-01-03 10:39:59', '2025-07-30 16:07:57', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(5, 'BUJOR Vasili', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sef directie proiectare aplicatii', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia proiectare aplicaţii', '+37322403020', '120', 'vasile.bujor@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770021', '2020-04-20 16:49:56', '1', '103', NULL, '2025-07-30 16:07:49', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(7, 'BULGAC Svetlana', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Șef direcție generală', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'empty field', '+37322403055', '155', 'svetlana.bulgac@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770007', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:01', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(11, 'GHEORGHIŢĂ Natalia', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Programator principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia proiectare aplicaţii', '+37322403050', '150', 'natalia.gheorghita@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770606', '2020-04-20 16:49:56', 'empty field', 'empty field', '2022-01-30 16:53:33', '2025-07-30 16:07:54', '2022-04-10 15:04:04', 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(12, 'ŢÎCU Andrei', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sef directie administrare a sistemului informational', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia administrare a sistemului informaţional', '+37322403039', '139', 'andrei.ticu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770019', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:08:02', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(13, 'Batrinac Artur', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Administrator principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'administrare sisteme informaționale', '+37322403029', '129', 'artur.batrinac@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770603', '2020-04-20 16:49:56', 'empty field', 'empty field', '2024-06-20 13:44:11', '2025-07-30 16:07:45', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(14, 'BURBULEA Ștefan', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Administrator principal rețea de calculatoare ', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia administrare a sistemului informaţional', '+37322403033', '133', 'stefan.burbulea@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770750', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:07:50', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(42, 'GALER Lilian', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sef directie generala', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'empty field', '+37322403105', '105', 'lilian.galer@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770012', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:34', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(43, 'CALINCU Dmitrii', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Șef adjunct direcție generală, Șef Direcția surse de date alternative și instrumente inovatoare în statistică', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'Direcția surse de date alternative și instrumente inovatoare în statistică', '+37322403139', '139', 'dmitrii.calincu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770089', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:37', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(44, 'ȚÎȚU Pavel', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Șef direcție', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'Direcția sisteme informaționale geografice', '+37322731531', 'empty field', 'pavel.titu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770084', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:09', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(46, 'CRĂCIUN Larisa', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Șef direcție', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'Direcția administrare şi achiziţii', '+37322403125', 'empty field', 'larisa.craciun@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770029', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:47', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(47, 'Pascari Cristina', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'statistica comertului interior', '+37322731745', 'empty field', 'cristina.pascari@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:17', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(58, 'Savva Janeta', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'statistica transporturilor, turismului si TIC', '+37322403028', 'empty field', 'janeta.savva@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770061', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:23', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(64, 'CUPRIANOVA Oxana', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcția statistica transporturilor și serviciilor', '+37322403102', 'empty field', 'oxana.cuprianova@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', '65 auto, 1 TR', '+37367770802', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:04', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(65, 'Hincu Ecaterina', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'statistica transporturilor, turismului si TIC', '+37322241467', 'empty field', 'ecaterina.hincu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', '1 B SC,1 A SC', '+37367770798', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:10', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(66, 'Rotaru Victoria', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'statistica transporturilor, turismului si TIC', '+37322731777', 'empty field', 'victoria.rotaru@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', '1 TUR, 1 INF', '+37367770049', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:22', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(68, 'TIMOFTI Iulia', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcția statistica transporturilor și serviciilor', '+37322403101', 'empty field', 'iulia.timofti@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'SERV TS, 3 COMERT', '+37367770062', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:35', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(69, 'Tarus Victoria', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'statistica comertului exterior', '+37322731745', 'empty field', 'victoria.tarus@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'SERV TS, 3 COMERT ', '+37367770058', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:34', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(70, 'PALII Emilia', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcția statistica turismului, tehnologiei informației și comunicațiilor', '+37322727905', 'empty field', 'emilia.palii@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', '1 - Auto', '+37367770796', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:15', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(71, 'ERMURACHI Galina', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sef directie', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica industriei şi energeticii', '+37322403058', '158', 'galina.ermurachi@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770045', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:07', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(82, 'VASILIŢA Elena', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica investiţiilor şi construcţiilor', '+37322727787', 'empty field', 'elena.vasilita@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770086', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:39', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(83, 'CANȚER Mariana', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica investiţiilor şi construcţiilor', '+37322403130', 'empty field', 'mariana.canter@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', '1-CC, CONS TS', '+37367770053', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:02', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(84, 'DEMIAN Elvira', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica investiţiilor şi construcţiilor', '+37322731883', 'empty field', 'elvira.demian@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770048', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:05', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(85, 'Stahi Irina', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'statistica investitiilor si constructiilor', '+37322731784', 'empty field', 'irina.stahi@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:30', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(86, 'MOCANU Oxana', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Șef direcție', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica structurală', '+37322403088', 'empty field', 'mocanu.oxana@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'ASA', '+37367770085', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:13', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(87, 'Petras Ludmila', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'statistica structurala', '+37322403089', 'empty field', 'ludmila.petras@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'ASA', '+37367770056', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:18', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(88, 'Gluscova Natalia', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sef directie', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'registre si clasificatoare', '+37322403034', '134', 'natalia.gluscova@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770825', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:08', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(89, 'Afteni Tatiana', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Programator principal ', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'proiectare aplicatii informatice', '+37322403089', '189', 'tatiana.afteni@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770060', '2020-04-20 16:49:56', 'empty field', 'empty field', '2021-11-12 05:32:45', '2025-07-30 16:07:42', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(90, 'Costin Olga', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'registre si clasificatoare', '+37322403087', '187', 'olga.costin@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770801', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:04', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(91, 'Dumbrava Tamara', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'registre si clasificatoare', '+37322403038', '138', 'tamara.dumbrava@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770799', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:06', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(92, 'Prihodico Liudmila', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'registre si clasificatoare', '+37322403036', '136', 'liudmila.prihodico@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770804', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:21', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(93, 'MUNTEAN Laura', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sef directie', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcția statistica turismului, tehnologiei informației și comunicațiilor', '+37322403028', 'empty field', 'laura.muntean@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770820', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:14', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(102, 'BATRÎNCEA Liudmila', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica investiţiilor şi construcţiilor', '+37322728180', 'empty field', 'ludmila.batrincea@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', '2-INVEST ANUL, 2-INVEST TRIM ', '+37367770054', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:00', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(109, 'Creciun  Vera', 'YYYYY', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Inginer principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'administrare sisteme informaționale', '+37322731866', 'empty field', 'vera.creciun@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', 'empty field', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:07:52', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(209, 'CHIHAI Elena', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Specialist principal', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica industriei şi energeticii', '+37322788275', 'empty field', 'elena.chihai@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770692', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:03', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(218, 'SPĂTARU Mihail', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'Direcția surse de date alternative și instrumente inovatoare în statistică', '+37322731531', 'empty field', 'mihai.spataru@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770799', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:12', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(245, 'SPÎNU Tatiana', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior ', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica structurală', '+37322788296', '', 'tatiana.spinu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'ASA', '+37367770659', '2020-04-20 16:49:56', '7', '712', '2020-08-27 09:15:36', '2025-07-30 16:09:29', '2020-08-27 09:17:18', 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(491, 'ONEA Maria', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sef adjunct  directie generala tehnologii informationale', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcția dezvoltare sisteme informaționale', '+37322403040', '140', 'maria.onea@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770027', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:07:59', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(509, 'LUPU Inga', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica industriei şi energeticii', '+37322403058', 'empty field', 'inga.lupu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770050', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:11', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(510, 'DĂNUȚĂ Oxana', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sef-adjunct directie', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'empty field', '+37322403083', 'empty field', 'oxana.danuta@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770001', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:49', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(511, 'UNRU Ludmila', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'Direcția evidență contabilă', '+37322403047', 'empty field', 'ludmila.unru@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770610', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:59', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(513, 'VIERU Maria', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'Direcția planificare', '+37322403047', 'empty field', 'maria.graur@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770090', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:07:00', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(514, 'Filimon Viorica', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'management financiar', '+37322403048', 'empty field', 'viorica.filimon@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770607', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:50', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(516, 'Hainitchi Tatiana', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sef directie', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'management financiar', '+37322403081', 'empty field', 'tatiana.hainitchi@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770816', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:53', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(517, 'Mucanov Nicolai', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Inginer principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'administrare sisteme informaționale', '+37322403031', '131', 'nicolai.mucanov@statistica.gov.md\r\n', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770672', '2020-04-20 16:49:56', 'empty field', 'empty field', '2021-10-03 08:07:44', '2025-07-30 16:07:58', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(522, 'GRIDNEVA Natalia', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica industriei şi energeticii', '+37322403133', '233', 'natalia.gridneva@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'IND TS, PRODMOLD A', '+37368061178', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:09', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(535, 'Tihon Daniel', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'metode statistice', '+37322403105', 'empty field', 'tihon.daniel@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770705', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:10', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(536, 'OSTAPENCO Galina', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Șef direcție', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'Direcția cercetări prin sondaj', '+37322403139', '139', 'galina.ostapenco@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770797', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:24', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(538, 'PLUGARI Ecaterina', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica industriei şi energeticii', '+37322731745', 'empty field', 'ecaterina.plugari@statistica.gov.md\r\n', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770052', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:20', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(550, 'Mardari Zinaida', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'statistica industriei si energeticii', '+37322729514', 'empty field', 'zinaida.mardari@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', '', '+37367770043', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:12', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(551, 'TURCULEȚ Svetlana', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica industriei şi energeticii', '+37322727679', 'empty field', 'svetlana.turculet@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770042', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:37', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(552, 'Panchevici Svetlana', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'statistica industriei si energeticii', '+37322727693', 'empty field', 'svetlana.panchevici@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770051', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:47', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(553, 'Serbinov Nelea', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'registre si clasificatoare', '+37322403037', '137', 'liudmila.prihodico@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770800', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:24', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(565, 'Crasov Maria', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'management financiar', '+37322403082', '182', 'maria.crasov@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770663', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:48', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(566, 'Busuioc Ecaterina', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'management financiar', '+37322403145', 'empty field', 'maria.crasov@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770049', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:46', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(567, 'LEAHU Mariana', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'Direcția evidență contabilă', '+37322403145', 'empty field', 'maria.crasov@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770816', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:54', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(568, 'BOBU Carina', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'Direcția administrare şi achiziţii', '+37322403127', 'empty field', 'carina.bobu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770087', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:44', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(569, 'Bivol Nicolae', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sofer', 'Directia generala management financiar', '0000-00-00', 'empty field', 'administrare si achizitii', 'management financiar', 'empty field', 'empty field', 'empty field', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770679', '2020-04-20 16:49:56', 'empty field', 'empty field', '2020-10-21 10:50:48', '2025-07-30 16:06:43', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(576, 'ŞUMOVA Liudmila', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Programator principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia proiectare aplicaţii', '+37322731866', 'empty field', 'ludmila.novicova@statistica.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770605', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:08:02', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(626, 'MELINCIUC Iuliana', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Administrator principal rețea de calculatoare ', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia administrare a sistemului informaţional', '+37322403040', '139', 'iuliana.melinciuc@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770602', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:07:56', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(640, 'Moraru Olga', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Sef sectie in cadrul directiei', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'metode statistice', '+37322403139', '139', 'olga.moraru@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770749', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:30', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(656, 'BUDEANU Roman', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Administrator principal rețea de calculatoare ', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia administrare a sistemului informaţional', '+37322403029', '129', 'roman.budeanu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770088', '2020-04-20 16:49:56', '1', 'empty field', NULL, '2025-07-30 16:07:48', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(660, 'BALAN Iurie', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcţia statistica industriei şi energeticii', '+37322403079', 'empty field', 'iurie.balan@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770609', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:08:59', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(668, 'Herghelegiu Doru-Marian', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Programator principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia proiectare aplicaţii', '+37322403021', '121', 'dorumarian.herghelegiu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37369847811', '2020-04-20 16:49:56', '1', '103', '2021-07-15 17:17:34', '2025-07-30 16:07:55', '2021-07-15 17:18:16', 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(669, 'Bors Daniela', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'metode statistice', '+37322403139', '139', 'empty field', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', 'empty field', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:40', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(670, 'NICA Viorica', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'Direcția cercetări prin sondaj', '+37322403139', '139', 'viorica.nica@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770647', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:28', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(696, 'Timbalist Catalin', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Programator principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'proiectare aplicatii informatice', '+37322403021', '121', 'catalin.timbalist@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367458519', '2020-04-20 16:49:56', '1', '103', '2024-12-18 05:31:46', '2025-07-30 16:08:04', '2021-07-15 17:18:16', 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(697, 'Tudor Popescu', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Programator principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'proiectare aplicatii informatice', '+37322403021', '121', 'tudor.popescu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37369847996', '2020-04-20 16:49:56', '1', '103', '2024-11-26 06:57:56', '2025-07-30 16:08:05', '2021-07-15 17:18:16', 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(699, 'AGATIEV Dumitru', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Programator principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia proiectare aplicaţii', '+37322403021', 'empty field', 'dumitru.agatiev@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367458519', '2025-04-15 07:23:21', '1', '103', NULL, '2025-07-30 16:07:43', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil.', 'empty field'),
	(702, 'Bîrlădeanu Natalia', 'yyyyy', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'dezvoltare sisteme informaționale', '+37322403021', 'empty field', 'natalia.birladeanu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37362071799', '2025-05-23 14:00:42', 'empty field', 'empty field', NULL, '2025-07-30 16:07:46', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil.', 'empty field'),
	(703, 'FRUNZE Dragoș', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Administrator principal rețea de calculatoare ', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia administrare a sistemului informaţional', '+37322403021', 'empty field', 'dragos.frunze@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770662', '2025-05-23 14:04:04', 'empty field', 'empty field', NULL, '2025-07-30 16:07:53', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil.', 'empty field'),
	(704, 'COSTIN Olga', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'Direcția surse de date alternative și instrumente inovatoare în statistică', '+37322403035', '139', 'olga.costin@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37368152181', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:35', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(705, 'OBREJA Vladislav', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'Direcția sisteme informaționale geografice', '+37322731531', 'empty field', 'vladislav.obreja@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367535700', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:26', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(706, 'ROTARU Grigore', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'Direcția cercetări prin sondaj', '+37322403139', '139', 'grigore.rotaru@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37368218991', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:19', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(707, 'SERBINOV Nelea', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant principal', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'Direcția surse de date alternative și instrumente inovatoare în statistică', '+37322403139', '139', 'nelea.serbinov@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770800', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:15', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(708, 'PUȘCAȘU Raisa', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'Direcția cercetări prin sondaj', '+37322403139', '139', 'raisa.puscasu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367734101', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:21', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(709, 'POPERECINAIA Silvia', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Șef direcție generală', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'empty field', '+37322403145', 'empty field', 'silvia.poperecinaia@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770077', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:55', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(710, 'ȚURCANU Cristina', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'Direcția planificare', '+37322403145', 'empty field', 'cristina.turcanu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770077', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:57', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(711, 'SOLTAN Victoria', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Consultant superior', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'Direcția evidență contabilă', '+37322403145', 'empty field', 'victoria.soltan@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37361198812', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:56', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(712, 'GOLBAN Vladimir', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Șofer', 'Directia generala management financiar', '0000-00-00', 'empty field', 'empty field', 'Direcția administrare şi achiziţii', '+37322403145', 'empty field', 'empty field', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770051', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:06:52', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(713, 'HÎNCU Diana', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Șef direcție', 'Directia generala statistica intreprinderilor', '0000-00-00', 'empty field', 'empty field', 'Direcția statistica transporturilor și serviciilor', '+37322403028', 'empty field', 'diana.hincu@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37369910070', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:09:10', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(714, 'VALCIUC Andrei', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Programator principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia proiectare aplicaţii', '+37322403021', '121', 'andrei.valciuc@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37369847996', '2020-04-20 16:49:56', '1', '103', '2021-07-15 17:17:34', '2025-07-30 16:08:07', '2021-07-15 17:18:16', 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(715, 'PALANCEAN Alex', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Programator principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia proiectare aplicaţii', '+37322403021', 'empty field', 'alex.palancean@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770747', '2025-04-15 07:23:21', '1', '103', NULL, '2025-07-30 16:08:01', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil.', 'empty field'),
	(716, 'BOLGARI Cristian', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Programator principal', 'Directia generala tehnologii informationale', '0000-00-00', 'empty field', 'empty field', 'Direcţia proiectare aplicaţii', '+37322403021', 'empty field', 'cristian.bolgari@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770603', '2025-04-15 07:23:21', '1', '103', NULL, '2025-07-30 16:07:47', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil.', 'empty field'),
	(717, 'CRASOV Maria', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Administrator principal rețea de calculatoare', 'Directia generala tehnologii informationale', '0000-00-00', 'Serviciul suport respondenți', 'empty field', 'empty field', '+37322403050', '150', 'maria.crasov@statistica.gov.md', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', '+37367770663', '2020-04-20 16:49:56', 'empty field', 'empty field', '2022-01-30 16:53:33', '2025-07-30 16:07:51', '2022-04-10 15:04:04', 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field'),
	(718, 'MANAGEMENTUL calității', 'xxxxx', 'BNS str. Grenoble, 106, MD-2019 Chisinau, Republica Moldova', 'Șef seccție', 'Directia generala metode si inovatii statistice', '0000-00-00', 'empty field', 'empty field', 'Secția managementul calității', 'empty field', 'empty field', 'empty field', 'Biroul Naţional de Statistică (BNS) este autoritate administrativă independentă instituţional şi profesional, creată pe lîngă Guvern în scopul coordonării sistemului statistic naţional privind dezvoltarea şi producerea statisticii oficiale.', 'empty field', 'empty field', '2020-04-20 16:49:56', 'empty field', 'empty field', NULL, '2025-07-30 16:24:32', NULL, 'Pentru vizualizarea informatiei complete despre angajat, accesati profilul. Click pe profil', 'empty field');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
