SELECT id, 
  CASE WHEN name REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS name_diacritice,
  CASE WHEN statut REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS statut_diacritice,
  CASE WHEN description REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS description_diacritice,
  CASE WHEN galaxy REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS galaxy_diacritice,
  CASE WHEN star REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS star_diacritice,
  CASE WHEN dob REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS dob_diacritice,
  CASE WHEN serviciu REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS serviciu_diacritice,
  CASE WHEN sectia REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS sectia_diacritice,
  CASE WHEN depart REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS depart_diacritice,
  CASE WHEN phone REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS phone_diacritice,
  CASE WHEN phoneinternal REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS phoneinternal_diacritice,
  CASE WHEN email REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS email_diacritice,
  CASE WHEN personalinfo REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS personalinfo_diacritice,
  CASE WHEN formname REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS formname_diacritice,
  CASE WHEN phonemobil REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS phonemobil_diacritice,
  CASE WHEN floor REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS floor_diacritice,
  CASE WHEN office REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS office_diacritice,
  CASE WHEN notice REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS notice_diacritice,
  CASE WHEN studio REGEXP '[ăâîșţĂÂÎȘŢ]' THEN 'da' ELSE 'nu' END AS studio_diacritice
FROM start3v5;
